- source/layouts/layout.erb
- source/stylesheets/_variables.scss
- source/stylesheets/screen.css.scss
> add a wrapper to the logo to give it some padding

- source/includes/_webhook_integration.md
- source/index.html.md
Copy/paste/markdown-ify from https://evocalize.atlassian.net/wiki/spaces/OFFICE/pages/180715535/Client+Leads+Webhook+Integration+Spec.
> Add webhook integration docs

- source/includes/_content_access_management.md
I did a copy pasta so any just need a second pair of eyes. :).
> added content access bulk call

- source/includes/_user_and_group_management_api.md
Documenting the facebook pages call.
> api docs for facebook pages call

- source/includes/_architecture_deep_linking.md
- source/index.html.md
Turns out we already have SSO/Auth documented (the JWT section), so I didn't do anything there.
There are a couple of things I still need to add, but I couldn't find the necessary information anywhere in confluence etc...so I'll need to ask someone who knows (Jim or Jesse maybe?):
* AutomatedProgram params
* Param for collapsing left nav
> adds architecture deep linking docs

- source/includes/_webhook_integration.md
Updates webhook docs for new channels.
> Update Webhook doc for new channels

- source/includes/_architecture_deep_linking.md
> updated deep linking text

- source/includes/_audiences.md
- source/includes/_facebook_audiences.md
- source/includes/_media.md
- source/includes/_user_and_group_management_api.md
- source/index.html.md
- Add Audience Manager API docs
- Add a note in Facebook Audiences API that it is deprecated
> Add Audience Manager API docs

- source/includes/_jwt_token.md
- source/index.html.md
clarify jwt orgslug usage and remove the signature instructions from the main page
>  Slug and Auth Updates.

- source/includes/_audiences.md
Include docs about new endpoints and hash csv data
- `POST /management/v1/audience/{placeholderId}/csv/upload`
multiform upload endpoint for partners to upload their hashed audience files
- `GET /management/v1/audience/{placeholderId}`
read endpoint for partners to fetch information on a placeholder and its channel audiences given a placeholder id
- Info on the data in the CSV being SHA-256 hashed
- More data identifiers in the CSV. `phone`, `firstname`, `lastname`
> update audience manager docs with more endpoints and hash csv info

- source/includes/_audiences.md
- source/includes/_errors.md
- source/includes/_request_and_response.md
- source/index.html.md
Add a `Shared Secret Authentication` section
Move request and response info to its own markdown file
Other changes:
- typos and small updates in audience docs
> add shared secret auth section

- source/includes/_access_control.md
- source/includes/_audiences.md
- source/includes/_content_access_management.md
- source/includes/_content_access_v2.md
- source/index.html.md
Adds access control documentation. Updates content and audience apis with this info as well.
> ME-4914 access control documentation

- source/includes/_architecture_deep_linking.md
looks like prettier fixed a few things also.
> add promo codes deeplink info

- source/includes/_webhook_integration.md
Adding new fields to webhook payload example.
> added new fields to webhook

- source/includes/_jwt_token.md
> add to the code sample here to show partners how they can SSO a user into a specific group.[ 
[UF-138](https://evocalize.atlassian.net/browse/UF-138)
> Updating SSO Auth Redirect example to include `path`

- source/includes/_architecture_deep_linking.md
- source/includes/_audiences.md
- add `contentFilter` to purchase creation deep link docs
- fix responses for `Get Audience Placeholder By ID` examples
> UF-274 add contentFilter param in program creation deeplink api section

- source/includes/_digital_asset_management.md
- source/includes/_user_and_group_management_api.md
⚠️⚠️⚠️⚠️⚠️⚠️⚠️⚠️⚠️⚠️DO NOT MERGE UNTIL 295 is in PRODUCTION⚠️⚠️⚠️⚠️⚠️⚠️⚠️⚠️⚠️⚠️
[UF-295](https://evocalize.atlassian.net/browse/UF-295)
- Also fixing a small omission in group endpoint
⚠️⚠️⚠️⚠️⚠️⚠️⚠️⚠️⚠️⚠️DO NOT MERGE UNTIL 295 is in PRODUCTION⚠️⚠️⚠️⚠️⚠️⚠️⚠️⚠️⚠️⚠️
> UF-295 - Creating partner API docs for bulk adding of media assets

- source/includes/_content_access_management.md
- source/includes/_content_access_v2.md
- source/includes/_content_management_api.md
Found some inconsistencies between the api and the docs when doing some load testing
> UF-472 fix content and content-item response status and resource paths

- source/includes/_user_and_group_management_api.md
Support associating users to team roles
> add team roles to partner api docs

- source/includes/_audiences.md
- source/includes/_user_and_group_management_api.md
> Consolidate audience pagination

- source/includes/_audiences.md
- source/includes/_errors.md
- source/includes/_orders.md
- source/index.html.md
Includes these APIs:
- Place Purchase/Subscription Order
- Edit Purchase/Subscription Order
- Cancel Order
- Get Order By ID
- Get Order Refund Preview By ID
also include google in audience section
> EP-1101 Order API docs

- .github/workflows/build.yml
- .github/workflows/deploy.yml
- .github/workflows/dev_deploy.yml
- source/includes/_orders.md
Update some deprecated github action values and also update the order API docs
> Update order api doc
